### ISSUE TITLE
server say "key too short" every times

### ISSUE THREAD

**Issue by mattn** [send-to/sendto#1]
while registration

```
Key too short
Your key must be at least 1000 characters long
```

**Comment by kennygrant** [comment]
I've fixed this to lower the limit to 500 characters, didn't want to allow blank keys and assumed everyone would be using longer keys. Let me know if that fixes it for you.

**Comment by mattn** [comment]
Still not. Probably, something wrong to handle the characters. Seems to be ignored.

**Comment by kennygrant** [comment]
Ah, sorry, I had a look and had put in a silly upper limit of 5k, which is not enough for some larger keys. Please try again now, I think this should be fixed. The message was reporting too short when it should have said too long.

**Comment by mattn** [comment]
thanks. I confirmed fix.
